import { TextView } from "view-state.slint";
import { MarkdownLine } from "../components/markdown.slint";

export global Settings {
    in property <[string]> monitors;
    in-out property <int> selected-monitor;
}

export struct Bible {
    id: string,
    name: string,
    english-name: string,
    installed: bool,
    installing: bool,
    progress: float,
}

export struct Verse {
    bible: Bible,
    book: string,
    chapter: int,
    part: int,
    verse: { a: int, b: int},
    text: string,
}

export global MainState {
    in property <bool> need-update;
    in-out property <[TextView]> saved-texts;
    in property <[Verse]> verses;
    in-out property <[Bible]> bibles;
    in property <[MarkdownLine]> last-changelog;
    in property <bool> show-changelog-on-start;

    callback search-bible(string);
    callback install-bible(string);
}
