@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct ViewBackgroundColor {
    a: color,
    b: color,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct ViewFontData {
    name: string,
    color: color,
    stroke: color,
    stroke-size: length,
    font-size: length,
}

export struct ViewData {
    path: string,
    tmp: bool,
    is-logo: bool,
    show-img: bool,
    color: ViewBackgroundColor,
    content: string,
    verse: string,
    img-bg: image,
    img-fit: ImageFit,
    font: ViewFontData,
    verse-font: ViewFontData,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct TextView {
    color: ViewBackgroundColor,
    content: string,
    font: ViewFontData,
}

export struct EditMode {
    editable: bool,
    row: int,
    col: int,
}

export global ViewState {
    in property <bool> off: false;

    in property <ViewData> select-media-preview: default-view-data();
    in-out property <ViewData> shared-view: default-view-data();
    in property <[[ViewData]]> media-list;
    in property <[string]> installed-fonts: [];

    in property <EditMode> in-edit-mode: {
        editable: false,
        row: -1,
        col: -1,
    };
    in property <length> window-width: 720px - 30px;
    in property <length> window-height: 423px - 30px;

    callback apply-changes(EditMode);
    callback select-file();

    callback show-logo();
    callback remove-media(int, int);
    callback preview-media(ViewData);
    callback sync-and-play(ViewData);

    public pure function default-view-data() -> ViewData {
        return {
            show-img: false,
            img-fit: ImageFit.contain,
            color: { a: Colors.black, b: Colors.black },
            font: {
                color: Colors.white,
                stroke: Colors.black,
                stroke-size: 2px,
                font-size: 120px,
            },
            verse-font: {
                color: Colors.white,
                stroke: Colors.black,
                stroke-size: 2px,
                font-size: 80px,
            },
        };
    }

    public pure function color-to-view(c: color) -> ViewBackgroundColor {
        return {
            a: c,
            b: c,
        };
    }

    public function set-shared-view(view-data: ViewData) {
        ViewState.shared-view.content = view-data.content;
        ViewState.shared-view.verse = view-data.verse;
        ViewState.shared-view.font = view-data.font;
        ViewState.shared-view.verse-font = view-data.verse-font;
        ViewState.shared-view.color = view-data.color;

        if view-data.show-img {
            ViewState.shared-view.show-img = view-data.show-img;
            ViewState.shared-view.img-bg = view-data.img-bg;
            ViewState.shared-view.img-fit = view-data.img-fit;
            ViewState.shared-view.path = view-data.path;
            ViewState.shared-view.is-logo = view-data.is-logo;
        }
    }
}
