import {
    VerticalBox,
    HorizontalBox,
    GridBox,
    ScrollView, TextEdit, LineEdit,
} from "std-widgets.slint";

import { ViewBackgroundColor } from "../api/view-state.slint";
import { InputCheck } from "input/check.slint";

component ColorSlider inherits Rectangle {
    height: 20px;
    border-radius: 10px;
    clip: true;

    in property <color> knob-color;
    in-out property <length> knob-position;
    in-out property <float> position;

    @children

    Rectangle {
        x: knob-position;
        width: 20px;
        height: parent.height;
        background: knob-color;
        border-radius: 10px;
        border-width: 5px;
        border-color: white;
    }

    TouchArea {
        moved => {
            position = Math.max(0, Math.min(1, self.mouse-x / parent.width));
        }
        clicked => {
            position = Math.max(0, Math.min(1, self.mouse-x / parent.width));
        }
    }
}

export component ColorPicker inherits Rectangle {
    height: show-preview ? 350px : 235px;

    in property <bool> allow-gradient: true;
    in property <bool> show-preview: false;
    property <bool> show-advanced: false;

    in-out property <ViewBackgroundColor> selected-color: {
        a: #3498db,
        b: #3498db,
    };

    out property <bool> gradient-mode: false;

    callback color-changed(ViewBackgroundColor);

    property <bool> editing-color-a: true;
    property <float> hue-a: 0.58;
    property <float> saturation-a: 0.7;
    property <float> lightness-a: 0.55;
    property <float> alpha-a: 1.0;
    property <float> hue-b: 0.58;
    property <float> saturation-b: 0.7;
    property <float> lightness-b: 0.55;
    property <float> alpha-b: 1.0;

    property <[[[float]]]> preset-hsls: [
        [
            // fila 0
            [0.0156, 0.781, 0.570, 1.0], // #e74c3c
            [0.0771, 0.797, 0.517, 1.0], // #e67e22
            [0.102, 0.903, 0.512, 1.0], // #f39c12
            [0.132, 0.889, 0.501, 1.0], // #f1c40f
            [0.404, 0.633, 0.490, 1.0], // #2ecc71
            [0.466, 0.757, 0.419, 1.0], // #1abc9c
            [0.469, 0.756, 0.356, 1.0], // #16a085
            [0.405, 0.632, 0.417, 1.0], // #27ae60
            [0.311, 0.815, 0.468, 1.0]  // #f39c12 (repetido)
        ],
        [
            // fila 1
            [0.567, 0.695, 0.531, 1.0], // #3498db
            [0.784, 0.389, 0.532, 1.0], // #9b59b6
            [0.584, 0.287, 0.286, 1.0], // #34495e
            [0.510, 0.088, 0.617, 1.0], // #95a5a6
            [0.000, 0.08, 0.935, 1.0], // #ecf0f1 (aprox)
            [0.000, 0.0, 0.0, 1.0], // #000000
            [0.566, 0.636, 0.443, 1.0], // #2980b9
            [0.784, 0.439, 0.467, 1.0], // #8e44ad
            [0.027, 0.632, 0.461, 1.0]  // #c0392b
        ]
    ];

    function color-to-hex(c: color) -> string {
        return "#" + int-to-hex(c.red) + int-to-hex(c.green) + int-to-hex(c.blue) + int-to-hex(c.alpha);
    }

    function int-to-hex(n: int) -> string {
        let hex-chars = [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F"
        ];
        let high = floor(n / 16);
        let low = mod(n, 16);
        return hex-chars[high] + hex-chars[low];
    }

    function hsl-to-color(h: float, s: float, l: float, a: float) -> color {
        return Colors.rgb(
            self.hsl-channel(h, s, l, 0),
            self.hsl-channel(h, s, l, 8),
            self.hsl-channel(h, s, l, 4)).with-alpha(a);
    }
    function hsl-channel(h: float, s: float, l: float, n: float) -> int {
        let k = mod((n + h * 12), 12);
        let a = s * min(l, 1 - l);
        let val = l - a * max(-1, min(k - 3, min(9 - k, 1)));
        return Math.round(val * 255);
    }

    function apply-hsla(hsla: [float]) {
        if (editing-color-a) {
            hue-a = hsla[0];
            saturation-a = hsla[1];
            lightness-a = hsla[2];
            alpha-a = hsla[3];
            if (!gradient-mode) {
                hue-b = hue-a;
                saturation-b = saturation-a;
                lightness-b = lightness-a;
                alpha-b = alpha-a;
            }
        } else {
            hue-b = hsla[0];
            saturation-b = hsla[1];
            lightness-b = hsla[2];
            alpha-b = hsla[3];
        }
        update-colors();
    }

    function update-colors() {
        if (gradient-mode) {
            selected-color = {
                a: hsl-to-color(hue-a, saturation-a, lightness-a, alpha-a),
                b: hsl-to-color(hue-b, saturation-b, lightness-b, alpha-b),
            };
        } else {
            let col = hsl-to-color(hue-a, saturation-a, lightness-a, alpha-a);
            selected-color = { a: col, b: col };
        }
        color-changed(selected-color);
    }

    VerticalBox {
        spacing: 1px;
        alignment: stretch;
        padding-top: 0px;
        padding-bottom: 0px;

        if show-preview: Rectangle {
            height: 60px;
            border-radius: 8px;
            border-width: 2px;
            border-color: #ccc;
            background: gradient-mode ? @linear-gradient(90deg, selected-color.a, selected-color.b) : selected-color.a;

            Text {
                font-size: 18px;
                text: gradient-mode ? color-to-hex(selected-color.a) + " ~ " + color-to-hex(selected-color.b) : color-to-hex(selected-color.a);
                horizontal-alignment: TextHorizontalAlignment.center;
                color: lightness-a > 0.5 ? #000000 : #ffffff;
            }
        }

        if allow-gradient: HorizontalBox {
            alignment: space-between;
            padding: 0px;

            VerticalLayout {
                // height: 52px;
                alignment: center;

                InputCheck {
                    label: "Modo Gradiente";
                    checked <=> gradient-mode;

                    changed checked => {
                        editing-color-a = true;
                        update-colors();
                    }
                }
            }

            if gradient-mode: HorizontalBox {
                spacing: 8px;
                alignment: stretch;

                Rectangle {
                    height: 20px;
                    border-radius: 6px;
                    background: editing-color-a ? #3498db : #ecf0f1;
                    VerticalLayout {
                        padding-left: 5px;
                        padding-right: 5px;
                        alignment: center;
                        Text {
                            text: "A";
                            color: editing-color-a ? white : #2c3e50;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }

                    TouchArea {
                        clicked => {
                            editing-color-a = true;
                        }
                    }
                }

                Rectangle {
                    height: 20px;
                    border-radius: 6px;
                    background: !editing-color-a ? #3498db : #ecf0f1;
                    VerticalLayout {
                        padding-left: 5px;
                        padding-right: 5px;
                        alignment: center;
                        Text {
                            text: "B";
                            color: !editing-color-a ? white : #2c3e50;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }

                    TouchArea {
                        clicked => {
                            editing-color-a = false;
                        }
                    }
                }
            }
        }

        ScrollView {
            horizontal-scrollbar-policy: always-off;
            vertical-stretch: 1;

            VerticalBox {
                spacing: 1px;
                alignment: start;
                padding-top: 0px;

                VerticalBox {
                    spacing: 8px;
                    Text {
                        text: "Colores Predefinidos";
                        font-size: 12px;
                        color: #7f8c8d;
                    }

                    VerticalLayout {
                        spacing: 6px;
                        for row in preset-hsls: HorizontalLayout {
                            spacing: 6px;
                            for p in row: Rectangle {
                                width: 30px;
                                height: 30px;
                                border-radius: 8px;
                                background: hsl-to-color(p[0], p[1], p[2], p[3]);
                                border-width: 2px;
                                border-color: #bdc3c7;
                                TouchArea {
                                    clicked => {
                                        if (editing-color-a) {
                                            selected-color.a = hsl-to-color(p[0], p[1], p[2], p[3]);
                                        } else {
                                            selected-color.b = hsl-to-color(p[0], p[1], p[2], p[3]);
                                        }

                                        apply-hsla(p);
                                    }
                                }
                            }
                        }
                    }
                }

                VerticalBox {
                    spacing: 4px;
                    Text {
                        text: "Matiz (Hue)";
                        font-size: 12px;
                        color: #7f8c8d;
                    }

                    ColorSlider {
                        background: @linear-gradient(90deg, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff, #ff0000);
                        knob-position: (editing-color-a ? hue-a : hue-b) * (parent.width - 36px);
                        knob-color: gradient-mode ? (editing-color-a ? selected-color.a : selected-color.b) : selected-color.a;

                        changed position => {
                            if (editing-color-a) {
                                hue-a = self.position;
                            } else {
                                hue-b = self.position;
                            }
                            update-colors();
                        }
                    }
                }

                HorizontalBox {
                    Rectangle {
                        Text {
                            color: #7f8c8d;
                            text: show-advanced ? "Hide Advanced Options" : "Show Advanced Options";
                        }

                        TouchArea {
                            clicked => {
                                show-advanced = !show-advanced;
                            }
                        }
                    }
                }
                
                // Saturation
                if show-advanced: VerticalBox {
                    spacing: 4px;
                    Text {
                        text: "Saturación";
                        font-size: 12px;
                        color: #7f8c8d;
                    }

                    ColorSlider {
                        background: @linear-gradient(90deg, #808080, hsl-to-color(editing-color-a ? hue-a : hue-b, 1, 0.5, 1));
                        knob-position: (editing-color-a ? saturation-a : saturation-b) * (parent.width - 36px);
                        knob-color: gradient-mode ? (editing-color-a ? selected-color.a : selected-color.b) : selected-color.a;

                        changed position => {
                            if (editing-color-a) {
                                saturation-a = self.position;
                            } else {
                                saturation-b = self.position;
                            }
                            update-colors();
                        }
                    }
                }
                
                // Lightness
                if show-advanced: VerticalBox {
                    spacing: 4px;
                    Text {
                        text: "Luminosidad";
                        font-size: 12px;
                        color: #7f8c8d;
                    }

                    ColorSlider {
                        background: @linear-gradient(90deg, #000000, hsl-to-color(editing-color-a ? hue-a : hue-b, editing-color-a ? saturation-a : saturation-b, 0.5, 1), #ffffff);
                        knob-position: (editing-color-a ? lightness-a : lightness-b) * (parent.width - 36px);
                        knob-color: gradient-mode ? (editing-color-a ? selected-color.a : selected-color.b) : selected-color.a;

                        changed position => {
                            if (editing-color-a) {
                                lightness-a = self.position;
                            } else {
                                lightness-b = self.position;
                            }
                            update-colors();
                        }
                    }
                }
                
                // Alpha
                if show-advanced: VerticalBox {
                    spacing: 4px;
                    Text {
                        text: "Transparencia";
                        font-size: 12px;
                        color: #7f8c8d;
                    }

                    ColorSlider {
                        background: @linear-gradient(90deg, transparent, hsl-to-color(editing-color-a ? hue-a : hue-b, editing-color-a ? saturation-a : saturation-b, editing-color-a ? lightness-a : lightness-b, 1));
                        knob-position: (editing-color-a ? alpha-a : alpha-b) * (parent.width - 36px);
                        knob-color: gradient-mode ? (editing-color-a ? selected-color.a : selected-color.b) : selected-color.a;

                        changed position => {
                            if (editing-color-a) {
                                alpha-a = self.position;
                            } else {
                                alpha-b = self.position;
                            }
                            update-colors();
                        }

                        Rectangle {
                            width: 100%;
                            height: 100%;
                            background: #ffffff;
                            for tile[i] in 20: Rectangle {
                                x: mod(i, 10) * (parent.width / 10);
                                y: floor(i / 10) * (parent.height / 2);
                                width: parent.width / 10;
                                height: parent.height / 2;
                                background: mod(i, 2) == mod(floor(i / 10), 2) ? #cccccc : #ffffff;
                            }
                        }

                        Rectangle {
                            width: 100%;
                            height: 100%;
                            background: @linear-gradient(90deg, transparent, hsl-to-color(editing-color-a ? hue-a : hue-b, editing-color-a ? saturation-a : saturation-b, editing-color-a ? lightness-a : lightness-b, 1));
                        }
                    }
                }
            }
        }
    }
}
