import {
    ColorPickerButton,
    ColorPickerPosition,
} from "color-picker-button.slint";
import { Palette, ComboBox } from "std-widgets.slint";
import { ViewData, ViewFontData, ViewState } from "../api/view-state.slint";
import { SliderLabel } from "input/slider-label.slint";

export component FontEditSection inherits VerticalLayout {
    spacing: 12px;

    in property <string> name;
    in property <ColorPickerPosition> color-popup-position;
    in-out property <ViewFontData> font;

    Rectangle {
        height: 35px;
        background: Palette.alternate-background;
        border-radius: 6px;

        HorizontalLayout {
            padding: 10px;
            Text {
                text: name;
                font-size: 15px;
                font-weight: 600;
                vertical-alignment: center;
            }
        }
    }

    HorizontalLayout {
        spacing: 20px;
        padding-left: 10px;
        padding-right: 10px;

        VerticalLayout {
            spacing: 6px;

            Text {
                text: "Texto";
                font-size: 13px;
                font-weight: 500;
            }

            ColorPickerButton {
                width: 40px;
                height: 40px;
                position: color-popup-position;
                allow-gradient: false;
                selected-color: ViewState.color-to-view(font.color);
                color-changed(color) => {
                    font.color = color.a;
                }
            }
        }

        VerticalLayout {
            spacing: 6px;

            Text {
                text: "Borde";
                font-size: 13px;
                font-weight: 500;
            }

            ColorPickerButton {
                width: 40px;
                height: 40px;
                position: color-popup-position;
                allow-gradient: false;
                selected-color: ViewState.color-to-view(font.stroke);
                color-changed(color) => {
                    font.stroke = color.a;
                }
            }
        }

        SliderLabel {
            width: 65%;
            minimum: 0;
            maximum: 50;
            sufix: "px";
            label: "Grosor";
            value: font.stroke-size / 1px;
            value-show: Math.round(font.stroke-size / 1px);
            changed value => {
                font.stroke-size = self.value * 1px;
            }
        }
    }

    HorizontalLayout {
        spacing: 20px;
        alignment: start;
        padding-left: 10px;
        padding-right: 10px;

        VerticalLayout {
            spacing: 6px;
            width: 45%;

            Text {
                text: "Fuente";
                font-size: 13px;
                font-weight: 500;
            }

            ComboBox {
                model: ViewState.installed-fonts;
                current-value: font.name;

                changed current-index => {
                    if self.current-index >= 0 && self.current-index < ViewState.installed-fonts.length {
                        font.name = ViewState.installed-fonts[self.current-index];
                    }
                }
            }
        }

        SliderLabel {
            width: 45%;
            minimum: 24;
            maximum: 1024;
            sufix: "px";
            label: "Tamaño de Fuente";
            value: font.font-size / 1px;
            value-show: Math.round(font.font-size / 1px);
            changed value => {
                font.font-size = self.value * 1px;
            }
        }
    }
}

export component FontEdit inherits VerticalLayout {
    alignment: start;
    spacing: 20px;

    in-out property <ViewData> data;
    in property <ColorPickerPosition> color-popup-position;

    FontEditSection {
        name: "📝 Fuente Principal (Contenido)";
        font: data.font;
        color-popup-position <=> color-popup-position;

        changed font => {
            data.font = self.font;
        }
    }

    FontEditSection {
        name: "📖 Fuente del Versículo";
        font: data.verse-font;
        color-popup-position <=> color-popup-position;

        changed font => {
            data.verse-font = self.font;
        }
    }
}
