import {
    VerticalBox,
    HorizontalBox,
    GridBox,
    ScrollView,
    Button,
    Palette,
} from "std-widgets.slint";
import { ColorPicker } from "color-picker.slint";
import { InputCheck } from "input/check.slint";

export component MediaSelector inherits VerticalLayout {
    alignment: start;
    padding: 10px;
    spacing: 10px;

    Rectangle {
        border-width: 2px;
        border-radius: 8px;
        border-color: Palette.alternate-background.brighter(0.4);
        background: Palette.alternate-background;

        VerticalLayout {
            padding-left: 50px;
            padding-right: 50px;
            padding-top: 50px;
            padding-bottom: 50px;

            Text {
                color: Palette.foreground;
                vertical-alignment: center;
                horizontal-alignment: center;
                text: "Haz click o arrastra un archivo para agregarlo";
            }
        }
    }

    InputCheck {
        label: "aksdhalkshdflkashdflkashdf";
    }

    ColorPicker {
    }
}
