import { Palette } from "std-widgets.slint";

export component Renderable inherits VerticalLayout {
    padding-left: 5px;
    padding-right: 5px;

    in property <duration> hover-wait: 200ms;
    in property <bool> selected;
    in property <bool> removable;
    in property <bool> editable;

    out property <bool> hover: false;

    callback preview();
    callback hover-preview();
    callback send-to-view();
    callback edit-click();
    callback remove-click();

    hover-timer := Timer {
        interval: hover-wait;

        triggered => {
            hover-preview();
            self.stop();
        }
    }

    Rectangle {
        background: Palette.alternate-background.brighter((hover || selected) ? 0.2 : 0.0);
        border-radius: 8px;

        TouchArea {
            clicked => preview();
            double-clicked => send-to-view();

            changed has-hover => {
                hover = self.has-hover;
                if self.has-hover {
                    hover-timer.start();
                } else {
                    hover-timer.stop();
                }
            }

            VerticalLayout {
                padding: 10px;

                @children
            }

            if hover: HorizontalLayout {
                y: 0px;
                x: parent.width - self.width;
                alignment: end;
                spacing: 5px;

                if editable: VerticalLayout {
                    alignment: start;

                    Rectangle {
                        border-radius: 8px;
                        background: Colors.gainsboro.brighter(i-edit-hover.has-hover ? 0.2 : 0.0);
                        VerticalLayout {
                            padding: 5px;

                            Image {
                                width: 16px;
                                height: 16px;
                                source: @image-url("../../icons/edit.svg");
                            }
                        }

                        i-edit-hover := TouchArea {
                            clicked => edit-click();
                        }
                    }
                }

                if removable: VerticalLayout {
                    alignment: start;

                    VerticalLayout {
                        Rectangle {
                            border-radius: 8px;
                            background: Colors.indianred.brighter(i-rm-hover.has-hover ? 0.2 : 0.0);

                            VerticalLayout {
                                padding: 5px;
                                i-rm-content := Image {
                                    width: 16px;
                                    height: 16px;
                                    source: @image-url("../../icons/remove.svg");
                                }
                            }

                            i-rm-hover := TouchArea {
                                clicked => remove-click();
                            }
                        }
                    }
                }
            }
        }
    }
}
