import {
    ListView,
    Button,
    TabWidget,
    ComboBox,
    TextEdit,
    Palette,
    LineEdit,
    ScrollView,
} from "std-widgets.slint";

import { ViewWindow } from "view.slint";
import { SettingsWindow } from "settings.slint";

import { Bible, Settings, Verse } from "api/global.slint";
import { FileItem, SongsState } from "api/songs.slint";
import { EditMode, ViewState, ViewBackgroundColor } from "api/view-state.slint";

import { View } from "components/view.slint";
import { MarkdownLine, MarkdownLineKind } from "components/markdown.slint";
import { ColorPicker } from "components/color-picker.slint";
import { Renderable, RenderableList } from "components/base/renderable.slint";
import { FileManagerDialog } from "dialogs/songs.slint";
import { MultimediaDialog } from "dialogs/media-selector.slint";
import { BiblesDialog } from "dialogs/bibles.slint";
import { FontEdit } from "components/font-edit.slint";
import { ColorPickerButton } from "components/color-picker-button.slint";
import { ChangelogDialog } from "dialogs/changelog.slint";

export { Bible, EditMode, FileItem, MarkdownLine, MarkdownLineKind, Settings, SettingsWindow, SongsState, Verse, ViewWindow, ViewState, ViewBackgroundColor }

export global MainState {
    in property <bool> need-update;
    in-out property <[string]> saved-texts;
    in property <[Verse]> verses;
    in-out property <[Bible]> bibles;
    in property <[MarkdownLine]> last-changelog;
    in property <bool> show-changelog-on-start;

    callback search-bible(string);
    callback install-bible(string);
}

export component MainWindow inherits Window {
    title: "Worship Screens";
    preferred-width: 720px;
    preferred-height: 423px;
    min-width: 1280px;

    in property <image> source;
    property <string> local-text;

    callback search-verse <=> search-verse-input.edited;

    callback start-window();
    callback open(string);
    callback open-release();

    callback shutdown-output();
    callback clear-output <=> clear-btn.clicked;
    callback clear-image <=> clear-img-btn.clicked;
    callback change-monitor <=> select-monitors.selected;

    callback send-to-view <=> send-btn.clicked;

    callback save-text(string);
    callback remove-saved-text(int);

    starter-timer := Timer {
        interval: 1s;
        triggered => {
            start-window();
            ViewState.window-width = preview.width;
            ViewState.window-height = preview.height;
            if MainState.show-changelog-on-start {
                dialog-changelog.show();
            }
            starter-timer.stop();
        }
    }

    HorizontalLayout {
        width: parent.width;
        height: parent.height;
        alignment: space-between;

        VerticalLayout {
            width: 70%;

            HorizontalLayout {
                spacing: 5px;
                padding-left: 10px;
                padding-top: 10px;
                padding-bottom: 10px;
                padding-right: 5px;

                if MainState.need-update: Button {
                    text: "Update Available";
                    primary: true;
                    clicked => open-release();
                }

                select-monitors := ComboBox {
                    model: Settings.monitors;
                    current-index: Settings.selected-monitor;
                }

                logo-btn := Button {
                    text: "Logo";
                    clicked => ViewState.show-logo();
                }

                shutdown-btn := Button {
                    text: ViewState.off ? "On" : "Off";
                    clicked => {
                        ViewState.off = !ViewState.off;
                        shutdown-output();
                    }
                }

                clear-btn := Button {
                    text: "Clear";
                }
            }

            Rectangle {
                width: 100%;
                height: 1px;
                background: Colors.dimgray.with-alpha(20%);
            }

            TabWidget {
                current-index: 0;

                Tab {
                    title: "Verses";

                    GridLayout {
                        spacing: 10px;
                        padding: 10px;
                        Row {
                            HorizontalLayout {
                                colspan: 3;
                                spacing: 10px;
                                alignment: stretch;

                                Button {
                                    text: "+";
                                    clicked => dialog-bibles.show();
                                }

                                search-verse-input := LineEdit {
                                    width: 95%;
                                    input-type: InputType.text;
                                    placeholder-text: "Busca: Juan 3:16, Romanos 14:10-14";
                                }
                            }
                        }

                        Row {
                            VerticalLayout {
                                colspan: 3;
                                verses-list := RenderableList {
                                    item-count: MainState.verses.length;
                                    item-focused(index) => {
                                        let e = MainState.verses[index];
                                        ViewState.shared-view.content = e.text;
                                        ViewState.shared-view.verse = e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? ":" + e.verse.a : "") : "");
                                        root.send-to-view();
                                    }
                                    ListView {
                                        for e[idx] in MainState.verses: vese-interactable := Renderable {
                                            padding-bottom: 10px;
                                            item-index: idx;
                                            focused-index: verses-list.current-focused;

                                            preview => {
                                                ViewState.shared-view.content = e.text;
                                                ViewState.shared-view.verse = e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? ":" + e.verse.a : "") : "");
                                            }
                                            send-to-view => {
                                                verses-list.focus();
                                                verses-list.current-focused = idx;
                                                ViewState.shared-view.content = e.text;
                                                ViewState.shared-view.verse = (e.part > 0 ? " [" + e.part + "] " : "") + e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? ":" + e.verse.a : "") : "");
                                                root.send-to-view();
                                            }

                                            VerticalLayout {
                                                spacing: 5px;

                                                Text {
                                                    font-size: 12px;
                                                    overflow: elide;
                                                    vertical-alignment: center;
                                                    color: Palette.foreground;
                                                    text: (e.part > 0 ? " [" + e.part + "] " : "") + e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? ":" + e.verse.a : "") : "");
                                                }

                                                Text {
                                                    font-size: 12px;
                                                    font-weight: 600;
                                                    vertical-alignment: center;
                                                    color: Palette.foreground.darker(60%);
                                                    text: ! e.bible.english-name.is-empty ? e.bible.english-name : e.bible.name;
                                                }

                                                Text {
                                                    text: e.text;
                                                    font-size: 16px;
                                                    font-weight: 600;
                                                    vertical-alignment: center;
                                                    color: Palette.foreground;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Tab {
                    title: "Songs";
                    HorizontalLayout {
                        VerticalLayout {
                            width: 40%;
                            padding: 10px;
                            spacing: 10px;
                            alignment: stretch;

                            HorizontalLayout {
                                spacing: 10px;
                                alignment: space-between;

                                Text {
                                    text: "Biblioteca de Canciones";
                                    vertical-alignment: center;
                                }

                                Button {
                                    text: "+";
                                    clicked => dialog-songs.show();
                                }
                            }

                            LineEdit {
                                placeholder-text: "Buscar canciones";
                                edited(s) => SongsState.on-search(s);
                            }

                            songs-list := RenderableList {
                                item-count: SongsState.songs.length;
                                item-focused(index) => {
                                    SongsState.select-song(index);
                                    SongsState.selected-paragraph = 0;
                                    ViewState.shared-view.content = SongsState.songs[index].content[0];
                                }
                                ListView {
                                    for s[idx] in SongsState.songs: song-interactable := Renderable {
                                        padding-bottom: 10px;
                                        selected: idx == SongsState.selected-song;
                                        item-index: idx;
                                        focused-index: songs-list.current-focused;

                                        preview => SongsState.select-song(idx);
                                        send-to-view => {
                                            songs-list.focus();
                                            songs-list.current-focused = idx;
                                            SongsState.select-song(idx);
                                            SongsState.selected-paragraph = 0;
                                            ViewState.shared-view.content = SongsState.songs[idx].content[0];
                                        }

                                        Text {
                                            text: s.path;
                                            vertical-alignment: center;
                                            color: Palette.foreground;
                                        }
                                    }
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: stretch;
                            padding: 10px;

                            if SongsState.selected-song >= 0: VerticalLayout {
                                spacing: 5px;

                                Text {
                                    text: SongsState.songs[SongsState.selected-song].path;
                                    font-size: 24px;
                                }
                            }

                            paragraphs-list := RenderableList {
                                item-count: SongsState.songs[SongsState.selected-song].content.length;
                                item-focused(index) => {
                                    ViewState.shared-view.content = SongsState.songs[SongsState.selected-song].content[index];
                                    SongsState.selected-paragraph = index;
                                    root.send-to-view();
                                }
                                ListView {
                                    for e[idx] in SongsState.songs[SongsState.selected-song].content: paragraph-interactable := Renderable {
                                        padding-bottom: 10px;
                                        selected: idx == SongsState.selected-paragraph;
                                        item-index: idx;
                                        focused-index: paragraphs-list.current-focused;

                                        preview => {
                                            ViewState.shared-view.content = e;
                                            SongsState.selected-paragraph = idx;
                                        }
                                        send-to-view => {
                                            paragraphs-list.focus();
                                            paragraphs-list.current-focused = idx;
                                            ViewState.shared-view.content = e;
                                            SongsState.selected-paragraph = idx;
                                            root.send-to-view();
                                        }

                                        Text {
                                            text: e;
                                            vertical-alignment: center;
                                            color: Palette.foreground;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Tab {
                    title: "Media";
                    VerticalLayout {
                        padding: 10px;
                        spacing: 10px;

                        HorizontalLayout {
                            spacing: 10px;
                            height: 50px;
                            alignment: space-between;

                            VerticalLayout {
                                Text {
                                    text: "Gestor de Medios";
                                    font-size: 24px;
                                }

                                Text {
                                    text: "Imagenes/Videos/Efectos";
                                }
                            }

                            Button {
                                text: "+";
                                clicked => {
                                    ViewState.select-media-preview = {
                                        show-img: false,
                                        tmp: false,
                                        is-logo: false,
                                        path: "",
                                        content: "",
                                        verse: "",
                                        img-fit: ImageFit.contain,
                                        color: { a: Colors.black, b: Colors.black },
                                        font: {
                                            color: Colors.white,
                                            stroke: Colors.black,
                                            stroke-size: 2px,
                                            font-size: 48px,
                                        },
                                        verse-font: {
                                            color: Colors.white,
                                            stroke: Colors.black,
                                            stroke-size: 2px,
                                            font-size: 24px,
                                        },
                                    };
                                    dialog-media-selector.show();
                                }
                            }
                        }

                        ListView {
                            for row[i] in ViewState.media-list: Rectangle {
                                height: (240px / 1.7) + 10px;

                                for e[n] in row: Renderable {
                                    x: n * self.width;
                                    width: 240px;
                                    height: self.width / 1.7;
                                    editable: true;
                                    removable: !e.tmp;

                                    preview => ViewState.preview-media(e);
                                    send-to-view => ViewState.sync-and-play(e);
                                    remove-click => ViewState.remove-media(i, n);
                                    edit-click => {
                                        ViewState.in-edit-mode = { editable: true, row: i, col: n };
                                        ViewState.select-media-preview = e;
                                        dialog-media-selector.show();
                                    }

                                    View {
                                        width: 100%;
                                        height: self.width / 1.7;
                                        data: e;

                                        if e.is-logo: Rectangle {
                                            x: 5px;
                                            y: 5px;
                                            width: 50px;
                                            height: 25px;
                                            border-radius: 4px;
                                            background: Palette.accent-background;

                                            Text {
                                                text: "LOGO";
                                                color: Colors.white;
                                                font-size: 10px;
                                                font-weight: 700;
                                                horizontal-alignment: center;
                                                vertical-alignment: center;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Tab {
                    title: "Text";

                    VerticalLayout {
                        padding: 10px;
                        spacing: 10px;
                        alignment: stretch;

                        HorizontalLayout {
                            spacing: 10px;
                            alignment: space-between;

                            Text {
                                text: "Contenido del Texto";
                                vertical-alignment: center;
                            }

                            HorizontalLayout {
                                spacing: 10px;
                                alignment: stretch;

                                Button {
                                    text: "Guardar";
                                    clicked => save-text(local-text);
                                }

                                Button {
                                    text: "Send";
                                    clicked => {
                                        ViewState.shared-view.content = local-text;
                                        send-to-view();
                                    }
                                }
                            }
                        }

                        TextEdit {
                            text: local-text;
                            placeholder-text: "Escribe tu mensaje aquí";
                            edited(text) => {
                                local-text = text;
                                ViewState.shared-view.content = text;
                            }
                        }

                        Text {
                            text: "Guardados";
                        }

                        saved-texts-list := RenderableList {
                            item-count: MainState.saved-texts.length;
                            item-focused(index) => {
                                ViewState.shared-view.content = MainState.saved-texts[index];
                                root.send-to-view();
                            }
                            ListView {
                                for e[idx] in MainState.saved-texts: r := Renderable {
                                    padding-bottom: 10px;
                                    item-index: idx;
                                    focused-index: saved-texts-list.current-focused;

                                    preview => {
                                        ViewState.shared-view.content = e;
                                    }
                                    send-to-view => {
                                        saved-texts-list.focus();
                                        saved-texts-list.current-focused = idx;
                                        ViewState.shared-view.content = e;
                                        root.send-to-view();
                                    }

                                    HorizontalLayout {
                                        alignment: space-between;

                                        Text {
                                            text: e;
                                            vertical-alignment: center;
                                            color: Palette.foreground;
                                        }

                                        Button {
                                            enabled: r.hover || r.has-focus;
                                            text: "Eliminar";
                                            clicked => remove-saved-text(idx);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            width: 1px;
            height: 100%;
            background: Colors.dimgray.with-alpha(20%);
        }

        VerticalLayout {
            width: 30%;
            padding: 10px;
            alignment: start;
            spacing: 10px;

            HorizontalLayout {
                spacing: 5px;
                alignment: end;

                clear-img-btn := Button {
                    visible: ViewState.shared-view.show-img;
                    text: "Stop Video/Image";
                }

                send-btn := Button {
                    text: "Send";
                }
            }

            preview := View {
                width: 100%;
                height: self.width / 1.7;
                window-height: 400px / 1.7;
                window-width: 400px;
                render-scale: 0.3;
                data <=> ViewState.shared-view;
            }

            ColorPickerButton {
                height: 60px;
                position: left;
                allow-gradient: true;
                selected-color: ViewState.shared-view.color;

                color-changed(color) => {
                    ViewState.shared-view.color = color;
                }
            }

            FontEdit {
                data <=> ViewState.shared-view;
            }
        }

        dialog-songs := FileManagerDialog {
            width: root.width;
            height: root.height;
            items: SongsState.songs-origin;
        }

        dialog-media-selector := MultimediaDialog {
            width: root.width;
            height: root.height;
        }

        dialog-bibles := BiblesDialog {
            width: root.width;
            height: root.height;
            bibles <=> MainState.bibles;
            search(query) => MainState.search-bible(query);
            install-bible(id) => MainState.install-bible(id);
        }

        dialog-changelog := ChangelogDialog {
            width: root.width;
            height: root.height;
            changelog: MainState.last-changelog;
            donate-clicked => open("https://github.com/biblionlabs/worship-screens");
            homepage-clicked => open("https://github.com/biblionlabs/worship-screens");
        }
    }
}
