import {
    ListView,
    Button,
    TabWidget,
    ComboBox,
    TextEdit,
    Palette,
    LineEdit,
} from "std-widgets.slint";

import { ViewWindow } from "view.slint";
import { SettingsWindow } from "settings.slint";

import { Bible, Settings, Verse } from "api/global.slint";
import { FileItem, SongsState } from "api/songs.slint";
import { ViewState, ViewType, ViewBackgroundColor } from "api/view-state.slint";

import { View } from "components/view.slint";
import { ColorPicker } from "components/color-picker.slint";
import { Renderable } from "components/base/renderable.slint";
import { FileManagerDialog } from "dialogs/songs.slint";

export { Bible, FileItem, Settings, SettingsWindow, SongsState, Verse, ViewWindow, ViewState, ViewBackgroundColor, ViewType }

export global MainState {
    in-out property <[string]> saved-texts;
    in property <[Verse]> verses;
}

export component MainWindow inherits Window {
    title: "Worship Screens";
    preferred-width: 720px;
    preferred-height: 423px;
    min-width: 1280px;

    in property <image> source;

    callback set-image();
    callback search-verse <=> search-verse-input.edited;

    callback start-window();
    callback open-settings <=> settings-btn.clicked;

    callback shutdown-output <=> shutdown-btn.clicked;
    callback clear-output <=> clear-btn.clicked;
    callback change-monitor <=> select-monitors.selected;

    callback send-to-view <=> send-btn.clicked;
    callback save-text();

    starter-timer := Timer {
        interval: 1s;
        triggered => {
            start-window();
            ViewState.window-width = preview.width;
            ViewState.window-height = preview.height;
            starter-timer.stop();
        }
    }

    HorizontalLayout {
        width: parent.width;
        height: parent.height;
        alignment: space-between;

        VerticalLayout {
            width: 70%;

            HorizontalLayout {
                spacing: 5px;
                padding-left: 10px;
                padding-top: 10px;
                padding-bottom: 10px;
                padding-right: 5px;

                settings-btn := Button {
                    text: "Settings";
                }

                select-monitors := ComboBox {
                    model: Settings.monitors;
                    current-index: Settings.selected-monitor;
                }

                logo-btn := Button {
                    text: "Logo";
                    clicked => set-image();
                }

                shutdown-btn := Button {
                    text: "Off";
                }

                clear-btn := Button {
                    text: "Clear";
                }
            }

            Rectangle {
                width: 100%;
                height: 1px;
                background: Colors.dimgray.with-alpha(20%);
            }

            TabWidget {
                current-index: 1;

                Tab {
                    title: "Verses";

                    GridLayout {
                        spacing: 10px;
                        padding: 10px;
                        Row {
                            search-verse-input := LineEdit {
                                colspan: 3;
                                input-type: InputType.text;
                                placeholder-text: "Busca: Juan 3:16, Romanos 14:10-14";
                            }
                        }

                        Row {
                            VerticalLayout {
                                colspan: 3;
                                ListView {
                                    for e in MainState.verses: vese-interactable := Renderable {
                                        padding-bottom: 10px;

                                        preview => {
                                            ViewState.content = e.text + "\n\n" + e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? "-" + e.verse.a + (e.verse.b > 0 ? ":" + e.verse.b : "") : "") : "");
                                        }
                                        send-to-view => {
                                            ViewState.content = e.text + "\n\n" + e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? "-" + e.verse.a + (e.verse.b > 0 ? ":" + e.verse.b : "") : "") : "");
                                            root.send-to-view();
                                        }

                                        VerticalLayout {
                                            spacing: 5px;

                                            Text {
                                                font-size: 12px;
                                                overflow: elide;
                                                vertical-alignment: center;
                                                color: Palette.foreground;
                                                text: (e.part > 0 ? " " + e.part + ". " : "") + e.book + (e.chapter > 0 ? " " + e.chapter + (e.verse.a > 0 ? "-" + e.verse.a + (e.verse.b > 0 ? ":" + e.verse.b : "") : "") : "");
                                            }

                                            Text {
                                                font-size: 12px;
                                                font-weight: 600;
                                                vertical-alignment: center;
                                                color: Palette.foreground.darker(60%);
                                                text: !e.bible.english-name.is-empty ? e.bible.english-name : e.bible.name;
                                            }

                                            Text {
                                                text: e.text;
                                                font-size: 16px;
                                                font-weight: 600;
                                                vertical-alignment: center;
                                                color: Palette.foreground;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Tab {
                    title: "Songs";
                    HorizontalLayout {
                        VerticalLayout {
                            width: 40%;
                            padding: 10px;
                            spacing: 10px;
                            alignment: stretch;

                            HorizontalLayout {
                                spacing: 10px;
                                alignment: space-between;

                                Text {
                                    text: "Biblioteca de Canciones";
                                    vertical-alignment: center;
                                }

                                Button {
                                    text: "+";
                                    clicked => dialog-songs.show();
                                }
                            }

                            LineEdit {
                                placeholder-text: "Buscar canciones";
                                edited(s) => SongsState.on-search(s);
                            }

                            ListView {
                                for s[idx] in SongsState.songs: song-interactable := Renderable {
                                    padding-bottom: 10px;
                                    selected: idx == SongsState.selected-song;

                                    preview => {
                                        SongsState.select-song(idx);
                                    }
                                    send-to-view => {
                                        SongsState.select-song(idx);
                                        SongsState.selected-paragraph = 0;
                                        ViewState.content = SongsState.songs[idx].content[0];
                                    }

                                    Text {
                                        text: s.path;
                                        vertical-alignment: center;
                                        color: Palette.foreground;
                                    }
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: stretch;
                            padding: 10px;

                            if SongsState.selected-song >= 0: VerticalLayout {
                                spacing: 5px;

                                Text {
                                    text: SongsState.songs[SongsState.selected-song].path;
                                    font-size: 24px;
                                }
                            }

                            ListView {
                                for e[idx] in SongsState.songs[SongsState.selected-song].content: paragraph-interactable := Renderable {
                                    padding-bottom: 10px;
                                    selected: idx == SongsState.selected-paragraph;

                                    preview => {
                                        ViewState.content = e;
                                        SongsState.selected-paragraph = idx;
                                    }
                                    send-to-view => {
                                        ViewState.content = e;
                                        SongsState.selected-paragraph = idx;
                                        root.send-to-view();
                                    }

                                    Text {
                                        text: e;
                                        vertical-alignment: center;
                                        color: Palette.foreground;
                                    }
                                }
                            }
                        }
                    }
                }

                Tab {
                    title: "Media";
                    VerticalLayout {
                        padding: 10px;
                        spacing: 10px;

                        HorizontalLayout {
                            spacing: 10px;
                            alignment: space-between;

                            VerticalLayout {
                                Text {
                                    text: "Gestor de Medios";
                                    font-size: 24px;
                                }

                                Text {
                                    text: "Imagenes/Videos/Efectos";
                                }
                            }

                            Button {
                                text: "+";
                            }
                        }

                        ListView {
                            for row in [
                                ["Porque..", "Jehová", "Jehová", "Jehová", "Jehová"],
                                ["Jehová", "Jehová", "Jehová", "Jehová", "Jehová"],
                                ["Jehová", "Jehová", "Jehová", "Jehová"],
                            ]: HorizontalLayout {
                                alignment: start;

                                for e in row: VerticalLayout {
                                    padding-left: 5px;
                                    padding-right: 5px;
                                    padding-bottom: 10px;

                                    Rectangle {
                                        background: #fff;
                                        border-radius: 8px;

                                        VerticalLayout {
                                            padding: 10px;

                                            Text {
                                                text: e;
                                                color: #000;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Tab {
                    title: "Text";

                    VerticalLayout {
                        padding: 10px;
                        spacing: 10px;
                        alignment: stretch;

                        HorizontalLayout {
                            spacing: 10px;
                            alignment: space-between;

                            Text {
                                text: "Contenido del Texto";
                                vertical-alignment: center;
                            }

                            HorizontalLayout {
                                spacing: 10px;
                                alignment: stretch;

                                Button {
                                    text: "Guardar";
                                    clicked => {
                                        save-text();
                                    };
                                }

                                Button {
                                    text: "Send";
                                    clicked => send-to-view();
                                }
                            }
                        }

                        TextEdit {
                            text <=> ViewState.content;
                            placeholder-text: "Escribe tu mensaje aquí";
                        }

                        Text {
                            text: "Guardados";
                        }

                        ListView {
                            for e in [
                                "Porque de tal manera amó Dios al mundo...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                                "Jehová es mi pastor; nada me faltará...",
                            ]: r := Renderable {
                                padding-bottom: 10px;

                                preview => {
                                    ViewState.content = e;
                                }
                                send-to-view => {
                                    ViewState.content = e;
                                    root.send-to-view();
                                }

                                HorizontalLayout {
                                    alignment: space-between;

                                    Text {
                                        text: e;
                                        vertical-alignment: center;
                                        color: Palette.foreground;
                                    }

                                    Button {
                                        enabled: r.hover;
                                        text: "Eliminar";
                                        clicked => {
                                            // TODO: Remove saved text
                                        };
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            width: 1px;
            height: 100%;
            background: Colors.dimgray.with-alpha(20%);
        }

        VerticalLayout {
            width: 30%;
            padding: 10px;
            alignment: start;
            spacing: 10px;

            HorizontalLayout {
                spacing: 5px;
                alignment: end;

                send-btn := Button {
                    text: "Send";
                }
            }

            preview := View {
                width: 100%;
                height: self.width / 1.7;
            }

            ColorPicker {
                show-preview: false;
                selected-color <=> ViewState.color;

                changed gradient-mode => {
                    if self.gradient-mode {
                        ViewState.view-type = ViewType.Linear;
                    } else {
                        ViewState.view-type = ViewType.Color;
                    }
                }
            }
        }

        dialog-songs := FileManagerDialog {
            width: root.width;
            height: root.height;
            items: SongsState.songs-origin;
        }
    }
}
