import {
    Button,
    ListView,
    ProgressIndicator,
    Palette,
    TextEdit,
    LineEdit,
} from "std-widgets.slint";
import { View } from "components/view.slint";
import { ViewState } from "api/view-state.slint";
import { Bible } from "api/global.slint";
import { Renderable } from "components/base/renderable.slint";

export component SettingsWindow inherits Window {
    title: "Worship Screens - Settings";
    width: 640px;
    min-height: 376px;

    in property <image> source;
    in property <[Bible]> bibles;

    callback select-bible <=> search-input.edited;
    callback search(string);
    callback close();
    callback save();

    init => {
        ViewState.window-width = preview.width;
        ViewState.window-height = preview.height;
    }

    VerticalLayout {
        width: parent.width;
        spacing: 10px;
        padding: 10px;
        alignment: stretch;

        Text {
            vertical-alignment: center;
            text: "Manage your installed bibles:";
        }

        search-input := LineEdit {
            placeholder-text: "Busca: Reina Valera 1960";
        }

        if bibles.length == 0: Text {
            text: search-input.text.is-empty ? "There are no Bibles in Database." : "There are no related Bibles.";
            min-height: 300px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        if bibles.length > 0: ListView {
            width: parent.width - (parent.padding * 2);
            min-height: 300px;
            max-height: 500px;

            for b in bibles: Renderable {
                padding-bottom: 10px;

                VerticalLayout {

                    HorizontalLayout {
                        padding: 10px;
                        alignment: space-between;

                        VerticalLayout {
                            spacing: 5px;

                            Text {
                                font-size: 18px;
                                vertical-alignment: center;
                                text: !b.english-name.is-empty ? b.english-name : b.name;
                                color: Palette.foreground;
                            }

                            if !b.name.is-empty: Text {
                                font-size: 14px;
                                vertical-alignment: center;
                                text: b.name;
                                color: Palette.foreground.darker(70%);
                            }
                        }

                        if !b.installed: Button {
                            enabled: !b.installing;
                            icon: @image-url("../assets/download.svg");
                            clicked => select-bible(b.id);
                        }
                    }

                    ProgressIndicator {
                        progress: b.progress;
                    }
                }
            }
        }

        Text {
            text: "Default Screen:";
            vertical-alignment: center;
        }

        preview := View {
            width: 100%;
            height: self.width / 1.7;
        }

        HorizontalLayout {
            alignment: end;
            spacing: 10px;
            padding-top: 10px;

            Button {
                text: "Cancel";
                clicked => root.close();
            }

            Button {
                text: "Save";
                clicked => root.save();
            }
        }
    }
}
