import { ViewState } from "api/view-state.slint";
import { View } from "components/view.slint";

export component ViewWindow inherits Window {
    title: "Worship Screens - View";

    preferred-width: 720px;
    preferred-height: 423px;

    TouchArea {
        mouse-cursor: none;

        View {
            width: 100%;
            height: 100%;
            data <=> ViewState.shared-view;
        }

        Rectangle {
            width: 100%;
            height: 100%;
            background: !ViewState.off ? Colors.transparent : Colors.black;

            animate background { duration: 500ms; }
        }
    }
}
